# Netlify Configuration File
[build]
  base = "mresh-salon"
  command = "npm run build:client"
  publish = "dist"

# Single Page Application (SPA) Routing Rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
